# -*- coding: utf-8 -*-
"""Residual_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWClHE08ylM5tVIq-PEQnpxerBgWYdvs
"""

print("GRU RESIDUAL NETWORK TRAINING")

# 1. Install & Import
!pip install -q dm-haiku jax jaxlib dill scikit-learn pandas matplotlib

import os
import glob
import time
import pandas as pd
import numpy as np
import dill as pickle
import joblib
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import jax
import jax.numpy as jnp
import haiku as hk
import functools

# Prevent JAX from hogging 100% of GPU memory so PyTorch can use it
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"] = "platform"

# Mount Drive
try:
    from google.colab import drive
    drive.mount('/content/drive')
    os.chdir('/content/drive/MyDrive/FYP_Training')
    print(f"Working directory: {os.getcwd()}")
except:
    pass

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"PyTorch Device: {device.type.upper()}")

# 2. Configuration
DATA_FOLDER      = "Dataset"
DELAN_MODEL_PATH = "TrainedModels/fyp_jax_delan_50_ckpt_2000.jax"
OUTPUT_DIR       = "ResidualModels"

os.makedirs(OUTPUT_DIR, exist_ok=True)
GRU_SAVE_PATH    = os.path.join(OUTPUT_DIR, "best_GRUResidual.pt")
SCALER_SAVE_PATH = os.path.join(OUTPUT_DIR, "feature_scaler.pkl")

# Data Headers
Q_COLS   = ['dp1', 'dp2', 'dp3']
QD_COLS  = ['dv1', 'dv2', 'dv3']
QDD_COLS = ['da1', 'da2', 'da3']
TAU_COLS = ['tau1', 'tau2', 'tau3']

# GRU Hyperparameters
SEQ_LEN = 128
INPUT_DIM = 12   # q(3) + qd(3) + qdd(3) + tau_delan(3)
HIDDEN_DIM = 64
N_LAYERS = 4
OUTPUT_DIM = 3   # tau_residual(3)
BATCH_SIZE = 1024
EPOCHS = 100
LEARNING_RATE = 0.001
PATIENCE = 15    # Early stopping

N_DOF = 3

# 3. Load Trained DeLaN (For Baseline Physics)
print(f"\n Loading DeLaN Baseline from {DELAN_MODEL_PATH}...")
with open(DELAN_MODEL_PATH, 'rb') as f:
    saved = pickle.load(f)
params, hyper = saved["params"], saved["hyper"]
activations = {'tanh': jnp.tanh, 'softplus': jax.nn.softplus}

def mass_matrix_fn(q, n_dof, shape, activation, epsilon, shift):
    n_output = int((n_dof ** 2 + n_dof) / 2)
    idx_diag = (np.arange(n_dof, dtype=int) + 1) * (np.arange(n_dof, dtype=int) + 2) // 2 - 1
    idx_tril = np.setdiff1d(np.arange(n_output), idx_diag)
    cat_idx = np.hstack((idx_diag, idx_tril))
    idx = np.argsort(cat_idx)
    mat_idx = np.tril_indices(n_dof)

    net = hk.nets.MLP(output_sizes=shape + (n_output,), activation=activation, name="mass_matrix")
    z = jnp.concatenate([jnp.cos(q), jnp.sin(q)], axis=-1)
    l_diagonal, l_off_diagonal = jnp.split(net(z), [n_dof,], axis=-1)
    l_diagonal = jax.nn.softplus(l_diagonal + shift) + epsilon
    vec_lower_triangular = jnp.concatenate((l_diagonal, l_off_diagonal), axis=-1)[..., idx]

    triangular_mat = jnp.zeros((n_dof, n_dof)).at[mat_idx].set(vec_lower_triangular)
    return jnp.matmul(triangular_mat, triangular_mat.transpose())

def kinetic_energy_fn(q, qd, n_dof, shape, activation, epsilon, shift):
    mass_mat = mass_matrix_fn(q, n_dof, shape, activation, epsilon, shift)
    return 0.5 * jnp.dot(qd, jnp.dot(mass_mat, qd))

def potential_energy_fn(q, shape, activation):
    net = hk.nets.MLP(output_sizes=shape + (1,), activation=activation, name="potential_energy")
    z = jnp.concatenate([jnp.cos(q), jnp.sin(q)], axis=-1)
    return net(z)

def structured_lagrangian_fn(q, qd, n_dof, shape, activation, epsilon, shift):
    e_kin = kinetic_energy_fn(q, qd, n_dof, shape, activation, epsilon, shift)
    e_pot = potential_energy_fn(q, shape, activation).squeeze()
    return e_kin - e_pot

def dynamics_model(params, key, q, qd, qdd, tau, lagrangian, n_dof):
    vmap_dim = (None, None, 0, 0)
    batch_matmul = jax.vmap(jnp.matmul, (0, 0))
    L, (dLdq, dLdqd) = jax.vmap(jax.value_and_grad(lagrangian, argnums=[2, 3]), vmap_dim)(params, key, q, qd)
    _, (d2L_dqddq, d2Ld2qd) = jax.vmap(jax.hessian(lagrangian, argnums=[2, 3]), vmap_dim)(params, key, q, qd)
    tau_pred = batch_matmul(d2Ld2qd, qdd) + batch_matmul(d2L_dqddq, qd) - dLdq
    return None, tau_pred, None, None

lagrangian_fn = hk.transform(functools.partial(
    structured_lagrangian_fn, n_dof=N_DOF, shape=(hyper['n_width'],) * hyper['n_depth'],
    activation=activations[hyper['activation']], epsilon=hyper['diagonal_epsilon'], shift=hyper['diagonal_shift']
))
lagrangian = lagrangian_fn.apply
delan_model = jax.jit(functools.partial(dynamics_model, lagrangian=lagrangian, n_dof=N_DOF))

# 4. Dataset Processing & Windowing
print("\n Processing CSVs and Calculating Residuals...")
csv_files = glob.glob(os.path.join(DATA_FOLDER, "*.csv"))

if len(csv_files) == 0:
    raise FileNotFoundError(f"No CSVs found in {DATA_FOLDER}")

# Shuffle files and split: 90% Train, 10% Validation
np.random.seed(42)
np.random.shuffle(csv_files)
split_idx = int(len(csv_files) * 0.9)
train_files = csv_files[:split_idx]
val_files = csv_files[split_idx:]

def process_files(file_list):
    raw_features_list = []
    residuals_list = []

    for f in file_list:
        try:
            df = pd.read_csv(f, index_col=0, header=None).T
        except:
            df = pd.read_csv(f, index_col=0, header=None, sep=r'\s+').T
        df = df.reset_index(drop=True).astype(float)

        q = df[Q_COLS].values
        qd = df[QD_COLS].values
        qdd = df[QDD_COLS].values
        tau_true = df[TAU_COLS].values

        # Get DeLaN prediction
        _, tau_delan, _, _ = delan_model(params, None, jnp.array(q), jnp.array(qd), jnp.array(qdd), jnp.zeros_like(q))
        tau_delan = np.array(tau_delan)

        # Calculate Target (Residual Error)
        tau_res = tau_true - tau_delan

        # Features: [q, qd, qdd, tau_delan]
        features = np.concatenate([q, qd, qdd, tau_delan], axis=1)

        raw_features_list.append(features)
        residuals_list.append(tau_res)

    return raw_features_list, residuals_list

train_features, train_residuals = process_files(train_files)
val_features, val_residuals = process_files(val_files)

# Fit Scaler on Training Data
print("Fitting StandardScaler and saving...")
scaler = StandardScaler()
all_train_features = np.concatenate(train_features, axis=0)
scaler.fit(all_train_features)
joblib.dump(scaler, SCALER_SAVE_PATH)

def create_windows(features_list, residuals_list, scaler):
    X_seq, y_seq = [], []
    for feats, res in zip(features_list, residuals_list):
        feats_scaled = scaler.transform(feats)
        for i in range(len(feats_scaled) - SEQ_LEN + 1):
            X_seq.append(feats_scaled[i : i + SEQ_LEN])
            y_seq.append(res[i + SEQ_LEN - 1]) # Target is the residual at the last timestep
    return np.array(X_seq), np.array(y_seq)

print("Creating 128-step sliding windows (This may take a moment)...")
X_train, y_train = create_windows(train_features, train_residuals, scaler)
X_val, y_val = create_windows(val_features, val_residuals, scaler)

print(f"Train Windows: {len(X_train)} | Val Windows: {len(X_val)}")

# 5. PyTorch Dataset & DataLoader
class RobotDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.FloatTensor(X)
        self.y = torch.FloatTensor(y)
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_loader = DataLoader(RobotDataset(X_train, y_train), batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(RobotDataset(X_val, y_val), batch_size=BATCH_SIZE, shuffle=False)

# 6. GRU Model Definition
class GRUResidual(nn.Module):
    def __init__(self):
        super().__init__()
        self.gru = nn.GRU(input_size=INPUT_DIM, hidden_size=HIDDEN_DIM,
                          num_layers=N_LAYERS, batch_first=True, dropout=0.1)
        self.fc = nn.Linear(HIDDEN_DIM, OUTPUT_DIM)

    def forward(self, x):
        h, _ = self.gru(x)
        # Take the output of the last timestep in the sequence
        return self.fc(h[:, -1, :])

model = GRUResidual().to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)

# 7. Training Loop
print("\n Starting GRU Training...")

best_val_loss = float('inf')
patience_counter = 0

train_losses, val_losses = [], []

for epoch in range(1, EPOCHS + 1):
    # Training
    model.train()
    batch_losses = []
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)

        optimizer.zero_grad()
        y_pred = model(X_batch)
        loss = criterion(y_pred, y_batch)
        loss.backward()
        optimizer.step()

        batch_losses.append(loss.item())

    train_loss = np.mean(batch_losses)
    train_losses.append(train_loss)

    # Validation
    model.eval()
    val_batch_losses = []
    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            val_loss = criterion(y_pred, y_batch)
            val_batch_losses.append(val_loss.item())

    val_loss = np.mean(val_batch_losses)
    val_losses.append(val_loss)

    print(f"Epoch {epoch:03d}/{EPOCHS} | Train Loss (MSE): {train_loss:.5f} | Val Loss: {val_loss:.5f}")

    # Early Stopping & Save Best Model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        patience_counter = 0
        torch.save(model.state_dict(), GRU_SAVE_PATH)
    else:
        patience_counter += 1

    if patience_counter >= PATIENCE:
        print(f"\n Early stopping triggered at Epoch {epoch}! No improvement in validation loss for {PATIENCE} epochs.")
        break

print(f"\n GRU Training Complete! Best model saved to: {GRU_SAVE_PATH}")
print(f"Scaler permanently saved to: {SCALER_SAVE_PATH}")

# ── 8. Plot Learning Curve ──
plt.figure(figsize=(10, 6))
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Validation Loss")
plt.title("GRU Training Learning Curve")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.yscale("log")
plt.legend()
plt.grid(True)
plt.savefig(os.path.join(OUTPUT_DIR, "GRU_Learning_Curve.png"))
plt.show()

print("\n Next Step: You can now test the final Hybrid Model using your batch inference script!")

# ============================================================================
# GRU + ATTENTION RESIDUAL NETWORK TRAINING
# ============================================================================
print(" TRAINING: GRU WITH ATTENTION MECHANISM")

ATTENTION_SAVE_PATH = os.path.join(OUTPUT_DIR, "best_GRUAttention.pt")

# 1. Define the Attention Architecture
class GRUAttentionResidual(nn.Module):
    def __init__(self):
        super().__init__()
        self.gru = nn.GRU(input_size=INPUT_DIM, hidden_size=HIDDEN_DIM,
                          num_layers=N_LAYERS, batch_first=True, dropout=0.1)

        # Attention specific layers
        self.W_a = nn.Linear(HIDDEN_DIM, HIDDEN_DIM, bias=False)
        self.v_a = nn.Linear(HIDDEN_DIM, 1, bias=False)

        self.fc = nn.Linear(HIDDEN_DIM, OUTPUT_DIM)

    def forward(self, x):
        # H shape: (batch_size, seq_len, hidden_dim)
        H, _ = self.gru(x)

        # Calculate attention scores
        # scores shape: (batch_size, seq_len)
        scores = self.v_a(torch.tanh(self.W_a(H))).squeeze(-1)

        # Calculate attention weights (alpha)
        alpha = torch.softmax(scores, dim=1)

        # Calculate context vector (weighted sum of hidden states)
        context = (alpha.unsqueeze(-1) * H).sum(dim=1)

        return self.fc(context)

#  2. Initialize Model, Loss, and Optimizer
attention_model = GRUAttentionResidual().to(device)
print(f" Built GRUAttentionResidual with {sum(p.numel() for p in attention_model.parameters())} parameters")

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(attention_model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)

#  3. Training Loop
print("\n Starting Attention GRU Training...")

best_attn_val_loss = float('inf')
patience_counter = 0

attn_train_losses, attn_val_losses = [], []

for epoch in range(1, EPOCHS + 1):
    # Training
    attention_model.train()
    batch_losses = []
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)

        optimizer.zero_grad()
        y_pred = attention_model(X_batch)
        loss = criterion(y_pred, y_batch)
        loss.backward()
        optimizer.step()

        batch_losses.append(loss.item())

    train_loss = np.mean(batch_losses)
    attn_train_losses.append(train_loss)

    # Validation
    attention_model.eval()
    val_batch_losses = []
    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = attention_model(X_batch)
            val_loss = criterion(y_pred, y_batch)
            val_batch_losses.append(val_loss.item())

    val_loss = np.mean(val_batch_losses)
    attn_val_losses.append(val_loss)

    print(f"Epoch {epoch:03d}/{EPOCHS} | Train Loss: {train_loss:.5f} | Val Loss: {val_loss:.5f}")

    # Early Stopping & Save Best Model
    if val_loss < best_attn_val_loss:
        best_attn_val_loss = val_loss
        patience_counter = 0
        torch.save(attention_model.state_dict(), ATTENTION_SAVE_PATH)
    else:
        patience_counter += 1

    if patience_counter >= PATIENCE:
        print(f"\n Early stopping triggered at Epoch {epoch}! No improvement for {PATIENCE} epochs.")
        break

print(f"\n Attention GRU Training Complete! Best model saved to: {ATTENTION_SAVE_PATH}")

#  4. Plot Attention Learning Curve
plt.figure(figsize=(10, 6))
plt.plot(attn_train_losses, label="Train Loss (Attention)", linestyle='-')
plt.plot(attn_val_losses, label="Validation Loss (Attention)", linestyle='--')
plt.title("Attention GRU Training Learning Curve")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.yscale("log")
plt.legend()
plt.grid(True)
plt.savefig(os.path.join(OUTPUT_DIR, "GRU_Attention_Learning_Curve.png"))
plt.show()